apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-devops-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-devops

  template:
    metadata:
      labels:
        app: hello-devops

    spec:
      containers:
        - name: hello-devops

          image: amrmhmd93/hello-devops:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 3000